services:
  - type: web
    name: bike-reservas-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bike-reservas-db
          property: connectionString

databases:
  - name: bike-reservas-db
    plan: free
